[
  {
    id: 1,
    token: '89j2de323djm2xx',
    gender: 'Male',
    name: 'Wade Warren',
    date_of_birth: 'August 5, 1987',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    email: 'fisdray@gmail.com',
    phone: '321-309-7416',
    country_code: 1,
    address:{
      country: 'Spain',
      state: 'Tarragona',
      city: 'Salou',
      zip_code: 43840,
    },
    Company: 'Foxmoor',
    employment: 'Marketing Coordinator',
    skill: 'Coordinator',
    online: true,
    Following: true,
    theme: {
      color: '#f44336',
    }
  },
  {
    id: 2,
    token: '9843f3mf34df9gr',
    gender: 'Female',
    name: 'Jane Cooper',
    date_of_birth: 'September 22, 1999',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    email: 'jane.cooper@mail.com',
    phone: '678-309-4357',
    country_code: 1,
    address:{
      country: 'United State',
      state: 'Washington',
      city: 'Kentucky',
      zip_code: 46533,
    },
    Company: 'Music Plus',
    employment: 'Dog Trainer',
    skill: 'Trainer',
    online: true,
    Following: false,
    theme: {
      color: '#c2185b',
    }
  },
  {
    id: 3,
    token: '6kf3f3mf34d33gr',
    gender: 'Male',
    name: 'Guy Hawkins',
    date_of_birth: 'October 13, 1995',
    avatar: 'https://randomuser.me/api/portraits/men/46.jpg',
    email: 'jane.cooper@mail.com',
    phone: '706-342-4061',
    country_code: 1,
    address:{
      country: 'United State',
      state: 'Alabama',
      city: 'Montgomery',
      zip_code: 15833,
    },
    Company: 'Chief Auto Parts',
    employment: 'Medical Assistant',
    skill: 'Assitant',
    online: false,
    Following: false,
    theme: {
      color: '#4a148c',
    }
  },
  {
    id: 4,
    token: 'ff9034kf3fmdswf',
    gender: 'Male',
    name: 'Robert Fox',
    date_of_birth: 'March 08, 1991',
    avatar: 'https://randomuser.me/api/portraits/men/47.jpg',
    email: 'robertfox@mail.com',
    phone: '213-952-0448',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Maine',
      city: 'Barbport',
      zip_code: 98736,
    },
    Company: 'Anderson Little',
    employment: 'Web Designer',
    skill: 'Work under pressure',
    online: false,
    Following: false,
    theme: {
      color: '#1e88e5',
    }
  },
  {
    id: 5,
    token: 'K94fmfdsklff932',
    gender: 'Female',
    name: 'Esther Howard',
    date_of_birth: 'July 14, 2000',
    avatar: 'https://randomuser.me/api/portraits/women/63.jpg',
    email: 'estherhoward@mail.com',
    phone: '870-318-6334',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'South Dakota',
      city: 'Weissnatshire',
      zip_code: 36750,
    },
    Company: 'Destiny Planners',
    employment: 'President of Sales',
    skill: 'Sales',
    online: true,
    Following: false,
    theme: {
      color: '#283593',
    }
  },
  {
    id: 6,
    token: 'dLJDIi49df4fd44',
    gender: 'Female',
    name: 'Loura Weber',
    date_of_birth: 'February 24, 1986',
    avatar: 'https://randomuser.me/api/portraits/women/64.jpg',
    email: 'estherhoward@mail.com',
    phone: '217-856-0403',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Maine',
      city: 'Sheltonbury',
      zip_code: 36750,
    },
    Company: 'Crandalls Fine Furniture',
    employment: 'Lead Manager',
    skill: 'Confidence',
    online: true,
    Following: false,
    theme: {
      color: '#4527a0',
    }
  },
  {
    id: 7,
    token: 'LDfrF04f454fgv4',
    gender: 'Male',
    name: 'Henry Kihn',
    date_of_birth: 'October 02, 1984',
    avatar: 'https://randomuser.me/api/portraits/men/86.jpg',
    email: 'henry.kihn@email.com',
    phone: '315-558-1826',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'North Carolina',
      city: 'Albatown',
      zip_code: 36750,
    },
    Company: 'Gas Legion',
    employment: 'Retail Administrator',
    skill: 'Leadership',
    online: false,
    Following: false,
    theme: {
      color: '#00838f',
    }
  },
  {
    id: 8,
    token: '98cvrkx43f3m4j3',
    gender: 'Male',
    name: 'Dawn Bashirian',
    date_of_birth: 'December 02, 1992',
    avatar: 'https://randomuser.me/api/portraits/men/35.jpg',
    email: 'henry.kihn@email.com',
    phone: '435-256-4921',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'New Mexico',
      city: 'New Dustiberg',
      zip_code: 87640,
    },
    Company: 'Cut Rite Lawn Care',
    employment: 'Advertising Orchestrator',
    skill: 'Self motivated',
    online: true,
    Following: false,
    theme: {
      color: '#ad1457',
    }
  },
  {
    id: 9,
    token: '34gf534mfg4dfHS',
    gender: 'Male',
    name: 'Antone Lakin',
    date_of_birth: 'November 02, 1984',
    avatar: 'https://randomuser.me/api/portraits/men/4.jpg',
    email: 'anotnelakin@email.com',
    phone: '315-558-1826',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'New Mexico',
      city: 'Carrollbury',
      zip_code: 92224,
    },
    Company: 'Kleinhans',
    employment: 'Global Banking Executive',
    skill: 'Executive',
    online: true,
    Following: false,
    theme: {
      color: '#558b2f',
    }
  },
  {
    id: 10,
    token: 'FFG9frjjfdjfF94',
    gender: 'Female',
    name: 'Carol Johnson',
    date_of_birth: 'November 02, 1996',
    avatar: 'https://randomuser.me/api/portraits/women/95.jpg',
    email: 'carol.johnson@email.com',
    phone: '775-334-4260',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Iowa',
      city: 'Toyborough',
      zip_code: 22341,
    },
    Company: 'Trak Auto',
    employment: 'Farming Administrator',
    skill: 'Fast learner',
    online: true,
    Following: false,
    theme: {
      color: '#ff9100',
    }
  },
  {
    id: 11,
    token: '834r823JJFx94fb',
    gender: 'Female',
    name: 'Sharon Moultrie',
    date_of_birth: 'January 02, 1994',
    avatar: 'https://randomuser.me/api/portraits/women/9.jpg',
    email: 'sharon.moultrie@email.com',
    phone: '503-879-6171',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'South Carolina',
      city: 'New Jackhaven',
      zip_code: 55463,
    },
    Company: 'Henrys Hamburgers',
    employment: 'Bulldozer Operator',
    skill: 'Operator',
    online: false,
    Following: true,
    theme: {
      color: '#4e342e',
    }
  },
  {
    id: 12,
    token: '8Uf34mfdfkdfsgb',
    gender: 'Female',
    name: 'Ashley Brown',
    date_of_birth: 'March 17, 1997',
    avatar: 'https://randomuser.me/api/portraits/women/10.jpg',
    email: 'ashley@email.com',
    phone: '252-264-2040',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Rhode Island',
      city: 'Lake Worth',
      zip_code: 10387,
    },
    Company: 'Leath Furniture',
    employment: 'Lead Construction Officer',
    skill: 'Networking skills',
    online: false,
    Following: false,
    theme: {
      color: '#424242',
    }
  },
  {
    id: 13,
    token: 'igkmer54745oe45',
    gender: 'Female',
    name: 'Linda Lamoreaux',
    date_of_birth: 'October 17, 1997',
    avatar: 'https://randomuser.me/api/portraits/women/11.jpg',
    email: 'linda.lamoreaux@email.com',
    phone: '503-879-6171',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Alabama',
      city: 'New Haven',
      zip_code: 78111,
    },
    Company: 'Dees Drive In',
    employment: 'Retail Director',
    skill: 'Technical savvy',
    online: true,
    Following: true,
    theme: {
      color: '#455a64',
    }
  },
  {
    id: 14,
    token: '9Freff384fm34fm',
    gender: 'Male',
    name: 'Chris Seay',
    date_of_birth: 'October 27, 1991',
    avatar: 'https://randomuser.me/api/portraits/men/12.jpg',
    email: 'chris.seay@email.com',
    phone: '252-264-1112',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Baltimore',
      city: 'Kuhlmantown',
      zip_code: 33390,
    },
    Company: 'Wilsons Jewelers',
    employment: 'Meteorologist',
    skill: 'Networking',
    online: false,
    Following: true,
    theme: {
      color: '#7b1fa2',
    }
  },
  {
    id: 15,
    token: 'FI90ifkjv567edr',
    gender: 'Male',
    name: 'Robert Jay Glennon',
    date_of_birth: 'February 24, 1960',
    avatar: 'https://randomuser.me/api/portraits/men/43.jpg',
    email: 'robert.jay@email.com',
    phone: '321-309-7416',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'South Dakota',
      city: 'Overland Park',
      zip_code: 66654,
    },
    Company: 'Morville',
    employment: 'Engraver',
    skill: 'Problem solving',
    online: true,
    Following: false,
    theme: {
      color: '#039be5',
    }
  },
  {
    id: 16,
    token: 'bcverfCewrfc943',
    gender: 'Male',
    name: 'Thomas Montano',
    date_of_birth: 'February 24, 1960',
    avatar: 'https://randomuser.me/api/portraits/men/91.jpg',
    email: 'ThomasNMontano@gustr.com',
    phone: '321-309-7416',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Virginia',
      city: 'Kelsiview',
      zip_code: 54355,
    },
    Company: 'Envirotecture Design Service',
    employment: 'Public relations specialist',
    skill: 'specialist',
    online: true,
    Following: false,
    theme: {
      color: '#00897b',
    }
  },
  {
    id: 17,
    token: 'fjenfwefw3r2nfw',
    gender: 'Male',
    name: 'Dennis Pickett',
    date_of_birth: 'March 10, 1981',
    avatar: 'https://randomuser.me/api/portraits/men/33.jpg',
    email: 'denis@gustr.com',
    phone: '336-272-9562',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Minnesota',
      city: 'Greensboro',
      zip_code: 12904,
    },
    Company: 'Smyths Homemakers',
    employment: 'Marketing Specialist',
    skill: 'Teamwork',
    online: true,
    Following: false,
    theme: {
      color: '#9e9d24',
    }
  },
  {
    id: 18,
    token: '73rj923fdmncsd3',
    gender: 'Male',
    name: 'James Soliu Meyers',
    date_of_birth: 'December 31, 1953',
    avatar: 'https://randomuser.me/api/portraits/men/34.jpg',
    email: 'james.soliu@mail.com',
    phone: '314-709-5916',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Stlouis',
      city: 'Hawks Nest',
      zip_code: 89566,
    },
    Company: 'Smyths Homemakers',
    employment: 'Marketing Liaison',
    skill: 'Technical savvy',
    online: true,
    Following: false,
    theme: {
      color: '#303f9f',
    }
  },
  {
    id: 19,
    token: 'x89jf34fm34f8fm',
    gender: 'Male',
    name: 'Casey McAllister',
    date_of_birth: 'August 01, 1986',
    avatar: 'https://randomuser.me/api/portraits/women/34.jpg',
    email: 'casey@publisher.com',
    phone: '951-245-1499',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Stlouis',
      city: 'Hawks Nest',
      zip_code: 32377,
    },
    Company: 'Komerci',
    employment: 'Respiratory therapist',
    skill: 'Leader',
    online: true,
    Following: false,
    theme: {
      color: '#512da8',
    }
  },
  {
    id: 20,
    token: 'jWpfFLJK49r4rff',
    gender: 'Male',
    name: 'Gloria White',
    date_of_birth: 'July 29, 1966',
    avatar: 'https://randomuser.me/api/portraits/women/35.jpg',
    email: 'gloria.white@mail.com',
    phone: '602-619-0420',
    country_code: 1,
    address:{
      country: 'United States',
      state: 'Phoenix',
      city: 'Dogwood Road',
      zip_code: 18711,
    },
    Company: 'Odyssey Records',
    employment: 'Auditor',
    skill: 'Engineer',
    online: true,
    Following: false,
    theme: {
      color: '#2962ff',
    }
  },
]
